export const SCENES = [
  // 北京市
  {
    slug: '故宫',
    name: '故宫',
    summary: '明清皇宫，紫禁城内外尽显皇家威仪与工艺结晶。',
    cover_url: 'assets/spots/Beijing_Gugong.avif',
    province: '北京市',
  },
  {
    slug: '长城',
    name: '长城',
    summary: '蜿蜒数千里的古代防御工程，纵横于华北群山之巅。',
    cover_url: 'assets/spots/Beijing_Changcheng.avif',
    province: '北京市',
  },
  {
    slug: '颐和园',
    name: '颐和园',
    summary: '皇家园林杰作，湖山相映的江南风韵与宫廷精致交融。',
    cover_url: 'assets/spots/Beijing_Yiheyuan.avif',
    province: '北京市',
  },
  {
    slug: '天坛',
    name: '天坛',
    summary: '明清两代皇帝祭天祈谷之所，坛庙轴线庄严典雅。',
    cover_url: 'assets/spots/Beijing_Tiantan.avif',
    province: '北京市',
  },
  // 天津市
  {
    slug: '古文化街',
    name: '古文化街',
    summary: '津门特色历史街区，传统民俗与手工艺荟萃。',
    cover_url: 'assets/spots/Tianjin_GuwenhuaJie.avif',
    province: '天津市',
  },
  {
    slug: '意式风情区',
    name: '意式风情区',
    summary: '欧式建筑街区，漫步间穿梭在近代天津的异域风情。',
    cover_url: 'assets/spots/Tianjin_YishiFengqingQu.avif',
    province: '天津市',
  },
  {
    slug: '海河',
    name: '海河',
    summary: '津城母亲河，欧式风貌与现代天际线相映。',
    cover_url: 'assets/spots/Tianjin_Haihe.avif',
    province: '天津市',
  },
  // 河北省
  {
    slug: '避暑山庄',
    name: '避暑山庄',
    summary: '承德皇家行宫，湖泊草原与殿宇相连的夏日避暑胜地。',
    cover_url: 'assets/spots/Hebei_Bishushanzhuang.avif',
    province: '河北省',
  },
  {
    slug: '山海关',
    name: '山海关',
    summary: '长城入海处的关城要塞，天下第一关名扬四海。',
    cover_url: 'assets/spots/Hebei_Shanhaiguan.avif',
    province: '河北省',
  },
  {
    slug: '赵州桥',
    name: '赵州桥',
    summary: '隋代敞肩石拱桥，千年仍在服役的古代工程奇迹。',
    cover_url: 'assets/spots/Hebei_ZhaozhouQiao.avif',
    province: '河北省',
  },
  // 上海市
  {
    slug: '外滩',
    name: '外滩',
    summary: '黄浦江畔万国建筑群，诉说着魔都的开埠与繁华。',
    cover_url: 'assets/spots/Shanghai_Waitan.avif',
    province: '上海市',
  },
  {
    slug: '东方明珠',
    name: '东方明珠',
    summary: '标志性电视塔，串联未来感球体的城市天际线地标。',
    cover_url: 'assets/spots/Shanghai_DongfangMingzhu.avif',
    province: '上海市',
  },
  {
    slug: '豫园',
    name: '豫园',
    summary: '江南典型古典园林，亭台楼阁与曲水假山巧妙呼应。',
    cover_url: 'assets/spots/Shanghai_Yuyuan.avif',
    province: '上海市',
  },
  // 山西省
  {
    slug: '平遥古城',
    name: '平遥古城',
    summary: '明清古韵保存完好，城墙巍然见证票号金融史。',
    cover_url: 'assets/spots/Shanxi_PingyaoGucheng.avif',
    province: '山西省',
  },
  {
    slug: '云冈石窟',
    name: '云冈石窟',
    summary: '北魏皇家佛教艺术瑰宝，岩壁佛像群气势恢宏。',
    cover_url: 'assets/spots/Shanxi_YungangShiku.avif',
    province: '山西省',
  },
  {
    slug: '悬空寺',
    name: '悬空寺',
    summary: '半嵌峭壁之上，木构奇技傍山飞架千年。',
    cover_url: 'assets/spots/Shanxi_Xuankongsi.avif',
    province: '山西省',
  },
  // 内蒙古自治区
  {
    slug: '呼伦贝尔',
    name: '呼伦贝尔',
    summary: '广袤草原与牧歌风情，四季景致辽阔壮丽。',
    cover_url: 'assets/spots/InnerMongolia_Hulunbuir.avif',
    province: '内蒙古自治区',
  },
  {
    slug: '额济纳',
    name: '额济纳',
    summary: '胡杨林金秋绚烂，河套绿洲的荒漠奇观。',
    cover_url: 'assets/spots/InnerMongolia_Ejina.avif',
    province: '内蒙古自治区',
  },
  {
    slug: '成吉思汗陵',
    name: '成吉思汗陵',
    summary: '草原文化象征，回望蒙古帝国的历史记忆。',
    cover_url: 'assets/spots/InnerMongolia_ChinggisMausoleum.avif',
    province: '内蒙古自治区',
  },
  // 辽宁省
  {
    slug: '沈阳故宫',
    name: '沈阳故宫',
    summary: '清初宫殿建筑群，满韵皇城气象独具。',
    cover_url: 'assets/spots/Liaoning_ShenyangGugong.avif',
    province: '辽宁省',
  },
  {
    slug: '大连星海广场',
    name: '大连星海广场',
    summary: '滨城地标巨擘，欧风海岸线开阔大气。',
    cover_url: 'assets/spots/Liaoning_DalianXinghai.avif',
    province: '辽宁省',
  },
  {
    slug: '本溪水洞',
    name: '本溪水洞',
    summary: '地下暗河奇景，乘舟探幽钟乳石林。',
    cover_url: 'assets/spots/Liaoning_BenxiShuidong.avif',
    province: '辽宁省',
  },
  // 吉林省
  {
    slug: '长白山',
    name: '长白山',
    summary: '天池雪峰与原始林海，火山地貌壮阔神秘。',
    cover_url: 'assets/spots/Jilin_Changbaishan.avif',
    province: '吉林省',
  },
  {
    slug: '雾凇岛',
    name: '雾凇岛',
    summary: '冬季雾凇胜景，银装素裹晶莹如梦。',
    cover_url: 'assets/spots/Jilin_Wusongdao.avif',
    province: '吉林省',
  },
  {
    slug: '净月潭',
    name: '净月潭',
    summary: '森林与湖泊相依，四季皆宜的城市后花园。',
    cover_url: 'assets/spots/Jilin_JingyueTan.avif',
    province: '吉林省',
  },
  // 黑龙江省
  {
    slug: '哈尔滨冰雪大世界',
    name: '哈尔滨冰雪大世界',
    summary: '冰灯雪雕童话王国，璀璨寒冬艺术殿堂。',
    cover_url: 'assets/spots/Heilongjiang_HarbinIce.avif',
    province: '黑龙江省',
  },
  {
    slug: '雪乡',
    name: '雪乡',
    summary: '厚积如棉的浪漫雪蘑菇，北国风光尽显。',
    cover_url: 'assets/spots/Heilongjiang_Xuexiang.avif',
    province: '黑龙江省',
  },
  {
    slug: '五大连池',
    name: '五大连池',
    summary: '火山堰塞湖群，地质公园生态多样。',
    cover_url: 'assets/spots/Heilongjiang_Wudalianchi.avif',
    province: '黑龙江省',
  },
  // 江苏省
  {
    slug: '苏州园林',
    name: '苏州园林',
    summary: '小中见大，叠石理水，咫尺山林的造园极致。',
    cover_url: 'assets/spots/Jiangsu_SuzhouGardens.avif',
    province: '江苏省',
  },
  {
    slug: '拙政园',
    name: '拙政园',
    summary: '江南园林典范，水院深深，亭台婉转。',
    cover_url: 'assets/spots/Jiangsu_Zhuozhengyuan.avif',
    province: '江苏省',
  },
  {
    slug: '夫子庙',
    name: '夫子庙',
    summary: '秦淮河畔文脉地标，市井烟火与古风交织。',
    cover_url: 'assets/spots/Jiangsu_Fuzimiao.avif',
    province: '江苏省',
  },
  {
    slug: '中山陵',
    name: '中山陵',
    summary: '青瓦白墙坐拥紫金山麓，近代史记忆丰碑。',
    cover_url: 'assets/spots/Jiangsu_Zhongshanling.avif',
    province: '江苏省',
  },
  // 浙江省
  {
    slug: '西湖',
    name: '西湖',
    summary: '苏堤春晓、断桥残雪，诗画江南的人间天堂。',
    cover_url: 'assets/spots/Zhejiang_Xihu.avif',
    province: '浙江省',
  },
  {
    slug: '乌镇',
    name: '乌镇',
    summary: '水网纵横的江南水乡，枕水人家古意盎然。',
    cover_url: 'assets/spots/Zhejiang_Wuzhen.avif',
    province: '浙江省',
  },
  {
    slug: '普陀山',
    name: '普陀山',
    summary: '海天佛国，梵音袅袅，山海间的清净圣地。',
    cover_url: 'assets/spots/Zhejiang_PutuoShan.avif',
    province: '浙江省',
  },
  {
    slug: '千岛湖',
    name: '千岛湖',
    summary: '星罗棋布的碧水岛屿，清澈见底的湖域天堂。',
    cover_url: 'assets/spots/Zhejiang_Qiandaohu.avif',
    province: '浙江省',
  },
  // 安徽省
  {
    slug: '黄山',
    name: '黄山',
    summary: '奇松、怪石、云海、温泉，四绝冠绝天下。',
    cover_url: 'assets/spots/Anhui_Huangshan.avif',
    province: '安徽省',
  },
  {
    slug: '宏村',
    name: '宏村',
    summary: '黛瓦白墙映月沼，徽派古村如诗如画。',
    cover_url: 'assets/spots/Anhui_Hongcun.avif',
    province: '安徽省',
  },
  {
    slug: '九华山',
    name: '九华山',
    summary: '佛教四大名山之一，梵宇云间香火绵延。',
    cover_url: 'assets/spots/Anhui_Jiuhuashan.avif',
    province: '安徽省',
  },
  // 福建省
  {
    slug: '鼓浪屿',
    name: '鼓浪屿',
    summary: '海岛洋楼与琴韵之城，浪漫文艺的慢时光。',
    cover_url: 'assets/spots/Fujian_Gulangyu.avif',
    province: '福建省',
  },
  {
    slug: '武夷山',
    name: '武夷山',
    summary: '丹霞峰林与九曲溪流，茶香氤氲的人间仙境。',
    cover_url: 'assets/spots/Fujian_Wuyishan.avif',
    province: '福建省',
  },
  {
    slug: '土楼',
    name: '土楼',
    summary: '客家人合院式夯土建筑，朴拙厚重的人文奇观。',
    cover_url: 'assets/spots/Fujian_Tulou.avif',
    province: '福建省',
  },
  // 江西省
  {
    slug: '庐山',
    name: '庐山',
    summary: '飞瀑云烟与人文胜迹，匡庐奇秀甲天下。',
    cover_url: 'assets/spots/Jiangxi_Lushan.avif',
    province: '江西省',
  },
  {
    slug: '景德镇',
    name: '景德镇',
    summary: '千年瓷都，柴窑青花照见匠心传承。',
    cover_url: 'assets/spots/Jiangxi_Jingdezhen.avif',
    province: '江西省',
  },
  {
    slug: '婺源',
    name: '婺源',
    summary: '油菜花海与徽派古村，最美乡村画卷。',
    cover_url: 'assets/spots/Jiangxi_Wuyuan.avif',
    province: '江西省',
  },
  // 山东省
  {
    slug: '泰山',
    name: '泰山',
    summary: '五岳之尊，登岱顶观云海揽河山。',
    cover_url: 'assets/spots/Shandong_Taishan.avif',
    province: '山东省',
  },
  {
    slug: '曲阜',
    name: '曲阜',
    summary: '孔庙孔府孔林，儒家文明的精神家园。',
    cover_url: 'assets/spots/Shandong_Qufu.avif',
    province: '山东省',
  },
  {
    slug: '崂山',
    name: '崂山',
    summary: '海上名山，奇峰险峻与碧海相依。',
    cover_url: 'assets/spots/Shandong_Laoshan.avif',
    province: '山东省',
  },
  // 河南省
  {
    slug: '少林寺',
    name: '少林寺',
    summary: '禅武合一的祖庭，塔林古柏见证千年。',
    cover_url: 'assets/spots/Henan_ShaolinSi.avif',
    province: '河南省',
  },
  {
    slug: '龙门石窟',
    name: '龙门石窟',
    summary: '伊河两岸佛像造像群，盛唐气象雕凿其上。',
    cover_url: 'assets/spots/Henan_LongmenShiku.avif',
    province: '河南省',
  },
  {
    slug: '云台山',
    name: '云台山',
    summary: '红石峡谷与叠瀑清潭，北方山水的灵动之美。',
    cover_url: 'assets/spots/Henan_Yuntaishan.avif',
    province: '河南省',
  },
  // 湖北省
  {
    slug: '黄鹤楼',
    name: '黄鹤楼',
    summary: '江畔名楼，诗意与传说穿越千年。',
    cover_url: 'assets/spots/Hubei_Huanghelou.avif',
    province: '湖北省',
  },
  {
    slug: '三峡大坝',
    name: '三峡大坝',
    summary: '世界级水利工程，巨坝横江壮观磅礴。',
    cover_url: 'assets/spots/Hubei_ThreeGorgesDam.avif',
    province: '湖北省',
  },
  {
    slug: '神农架',
    name: '神农架',
    summary: '原始森林秘境，生物多样性的天然宝库。',
    cover_url: 'assets/spots/Hubei_Shennongjia.avif',
    province: '湖北省',
  },
  // 湖南省
  {
    slug: '张家界',
    name: '张家界',
    summary: '石英砂岩峰林奇绝，阿凡达取景地梦幻异境。',
    cover_url: 'assets/spots/Hunan_Zhangjiajie.avif',
    province: '湖南省',
  },
  {
    slug: '岳阳楼',
    name: '岳阳楼',
    summary: '洞庭天下水，岳阳天下楼，文脉绵长。',
    cover_url: 'assets/spots/Hunan_YueyangLou.avif',
    province: '湖南省',
  },
  {
    slug: '凤凰古城',
    name: '凤凰古城',
    summary: '沱江水绕吊脚楼，苗疆古镇夜色如梦。',
    cover_url: 'assets/spots/Hunan_FenghuangGucheng.avif',
    province: '湖南省',
  },
  // 广东省
  {
    slug: '广州塔',
    name: '广州塔',
    summary: '又称小蛮腰，珠江夜色中的城市新地标。',
    cover_url: 'assets/spots/Guangdong_GuangzhouTa.avif',
    province: '广东省',
  },
  {
    slug: '丹霞山',
    name: '丹霞山',
    summary: '丹霞地貌典型区，赤壁丹崖艳丽多姿。',
    cover_url: 'assets/spots/Guangdong_Danxiashan.avif',
    province: '广东省',
  },
  {
    slug: '白云山',
    name: '白云山',
    summary: '南粤名山，云山珠水城市绿肺。',
    cover_url: 'assets/spots/Guangdong_Baiyunshan.avif',
    province: '广东省',
  },
  // 广西壮族自治区
  {
    slug: '桂林山水',
    name: '桂林山水',
    summary: '喀斯特峰丛江流，山青水秀甲天下。',
    cover_url: 'assets/spots/Guangxi_GuilinShanshui.avif',
    province: '广西壮族自治区',
  },
  {
    slug: '阳朔西街',
    name: '阳朔西街',
    summary: '中西合璧的休闲小镇，背倚漓江山水画廊。',
    cover_url: 'assets/spots/Guangxi_YangshuoXijie.avif',
    province: '广西壮族自治区',
  },
  {
    slug: '德天瀑布',
    name: '德天瀑布',
    summary: '中越边境跨国瀑布，水幕轰鸣气势磅礴。',
    cover_url: 'assets/spots/Guangxi_DetianPubu.avif',
    province: '广西壮族自治区',
  },
  // 海南省
  {
    slug: '三亚',
    name: '三亚',
    summary: '热带滨海度假胜地，阳光海滩与椰风海韵。',
    cover_url: 'assets/spots/Hainan_Sanya.avif',
    province: '海南省',
  },
  {
    slug: '亚龙湾',
    name: '亚龙湾',
    summary: '半月形海湾，沙细浪缓，潜水胜地。',
    cover_url: 'assets/spots/Hainan_YalongWan.avif',
    province: '海南省',
  },
  {
    slug: '蜈支洲岛',
    name: '蜈支洲岛',
    summary: '海水清澈见底，珊瑚礁环绕的潜水天堂。',
    cover_url: 'assets/spots/Hainan_WuzhizhouDao.avif',
    province: '海南省',
  },
  // 重庆市
  {
    slug: '洪崖洞',
    name: '洪崖洞',
    summary: '依崖而建的吊脚楼群，山城立体夜景名片。',
    cover_url: 'assets/spots/Chongqing_Hongyadong.avif',
    province: '重庆市',
  },
  {
    slug: '磁器口',
    name: '磁器口',
    summary: '古镇石板路与巴渝风情，小吃与市井交织。',
    cover_url: 'assets/spots/Chongqing_Ciqikou.avif',
    province: '重庆市',
  },
  {
    slug: '长江索道',
    name: '长江索道',
    summary: '跨江空中走廊，俯瞰两岸立体山城风貌。',
    cover_url: 'assets/spots/Chongqing_ChangjiangSuodao.avif',
    province: '重庆市',
  },
  // 四川省
  {
    slug: '宽窄巷子',
    name: '宽窄巷子',
    summary: '老成都生活样本，青瓦灰墙的闲适雅致。',
    cover_url: 'assets/spots/Sichuan_KuanzhaiXiangzi.avif',
    province: '四川省',
  },
  {
    slug: '九寨沟',
    name: '九寨沟',
    summary: '五彩池与瀑布群，四季如画的人间仙境。',
    cover_url: 'assets/spots/Sichuan_Jiuzhaigou.avif',
    province: '四川省',
  },
  {
    slug: '峨眉山',
    name: '峨眉山',
    summary: '云海佛光金顶雪，林海古刹清凉世界。',
    cover_url: 'assets/spots/Sichuan_EMeiShan.avif',
    province: '四川省',
  },
  {
    slug: '都江堰',
    name: '都江堰',
    summary: '古代水利工程奇迹，岷江水润川西平原。',
    cover_url: 'assets/spots/Sichuan_Dujiangyan.avif',
    province: '四川省',
  },
  // 西藏自治区
  {
    slug: '布达拉宫',
    name: '布达拉宫',
    summary: '雪域高原圣城地标，红白宫辉映藏地文明。',
    cover_url: 'assets/spots/Tibet_PutalaGong.avif',
    province: '西藏自治区',
  },
  {
    slug: '纳木错',
    name: '纳木错',
    summary: '念青唐古拉山脚下的圣湖，湛蓝纯净如镜。',
    cover_url: 'assets/spots/Tibet_Namucuo.avif',
    province: '西藏自治区',
  },
  {
    slug: '珠峰大本营',
    name: '珠峰大本营',
    summary: '仰望世界之巅，皑皑雪峰触手可及。',
    cover_url: 'assets/spots/Tibet_ZhufengDibenying.avif',
    province: '西藏自治区',
  },
  // 陕西省
  {
    slug: '兵马俑',
    name: '兵马俑',
    summary: '秦始皇陵地下军阵，青铜与陶俑的帝国威仪。',
    cover_url: 'assets/spots/Shaanxi_Bingmayong.avif',
    province: '陕西省',
  },
  {
    slug: '华清池',
    name: '华清池',
    summary: '温泉御苑，杨贵妃与盛唐故事的舞台。',
    cover_url: 'assets/spots/Shaanxi_Huaqingchi.avif',
    province: '陕西省',
  },
  {
    slug: '大雁塔',
    name: '大雁塔',
    summary: '玄奘取经留迹处，千年古塔俯瞰长安。',
    cover_url: 'assets/spots/Shaanxi_DayanTa.avif',
    province: '陕西省',
  },
  {
    slug: '华山',
    name: '华山',
    summary: '奇险天下第一山，绝壁栈道惊险绝伦。',
    cover_url: 'assets/spots/Shaanxi_Huashan.avif',
    province: '陕西省',
  },
  // 甘肃省
  {
    slug: '敦煌',
    name: '敦煌',
    summary: '大漠孤烟直，月牙泉与鸣沙山相依。',
    cover_url: 'assets/spots/Gansu_Dunhuang.avif',
    province: '甘肃省',
  },
  {
    slug: '莫高窟',
    name: '莫高窟',
    summary: '丝绸之路上的艺术宝库，洞窟壁画辉煌璀璨。',
    cover_url: 'assets/spots/Gansu_MogaoKu.avif',
    province: '甘肃省',
  },
  {
    slug: '嘉峪关',
    name: '嘉峪关',
    summary: '长城西端雄关，关城挺拔望玉门。',
    cover_url: 'assets/spots/Gansu_Jiayuguan.avif',
    province: '甘肃省',
  },
  {
    slug: '张掖丹霞',
    name: '张掖丹霞',
    summary: '七彩丘陵如画，彩带叠嶂流霞溢彩。',
    cover_url: 'assets/spots/Gansu_ZhangyeDanxia.avif',
    province: '甘肃省',
  },
  // 青海省
  {
    slug: '青海湖',
    name: '青海湖',
    summary: '高原湛蓝大湖，草海油菜花相映成辉。',
    cover_url: 'assets/spots/Qinghai_QinghaiHu.avif',
    province: '青海省',
  },
  {
    slug: '茶卡盐湖',
    name: '茶卡盐湖',
    summary: '天空之境倒影如镜，盐晶银白无垠。',
    cover_url: 'assets/spots/Qinghai_ChakaYanhua.avif',
    province: '青海省',
  },
  {
    slug: '塔尔寺',
    name: '塔尔寺',
    summary: '黄教名刹，堆绣与酥油花艺术绝伦。',
    cover_url: 'assets/spots/Qinghai_Taersi.avif',
    province: '青海省',
  },
  // 宁夏回族自治区
  {
    slug: '沙坡头',
    name: '沙坡头',
    summary: '大漠黄河相拥，治沙与旅游并举。',
    cover_url: 'assets/spots/Ningxia_Shapotou.avif',
    province: '宁夏回族自治区',
  },
  {
    slug: '沙湖',
    name: '沙湖',
    summary: '沙与湖相依的独特景观，候鸟乐园。',
    cover_url: 'assets/spots/Ningxia_Shahu.avif',
    province: '宁夏回族自治区',
  },
  {
    slug: '镇北堡',
    name: '镇北堡',
    summary: '西部影城古堡群，电影与黄土风貌交汇。',
    cover_url: 'assets/spots/Ningxia_Zhenbeibao.avif',
    province: '宁夏回族自治区',
  },
  // 新疆维吾尔自治区
  {
    slug: '喀纳斯',
    name: '喀纳斯',
    summary: '高山冷杉与变色湖，童话森林秘境。',
    cover_url: 'assets/spots/Xinjiang_Kanas.avif',
    province: '新疆维吾尔自治区',
  },
  {
    slug: '天山天池',
    name: '天山天池',
    summary: '雪峰之下碧玉湖，天山明珠。',
    cover_url: 'assets/spots/Xinjiang_TianshanTianchi.avif',
    province: '新疆维吾尔自治区',
  },
  {
    slug: '赛里木湖',
    name: '赛里木湖',
    summary: '大西洋最后一滴眼泪，花海草甸环湖如画。',
    cover_url: 'assets/spots/Xinjiang_SailimuHu.avif',
    province: '新疆维吾尔自治区',
  },
  {
    slug: '火焰山',
    name: '火焰山',
    summary: '吐鲁番赤红山岭，热浪滚滚名震西域。',
    cover_url: 'assets/spots/Xinjiang_Huoyanshan.avif',
    province: '新疆维吾尔自治区',
  },
  // 台湾省
  {
    slug: '台北',
    name: '台北',
    summary: '都会与人文交织，夜市小吃与古迹博物馆并存。',
    cover_url: 'assets/spots/Taiwan_Taibei.avif',
    province: '台湾省',
  },
  {
    slug: '日月潭',
    name: '日月潭',
    summary: '群山环绕碧波心，晨雾缭绕静谧如诗。',
    cover_url: 'assets/spots/Taiwan_RiyueTan.avif',
    province: '台湾省',
  },
  {
    slug: '阿里山',
    name: '阿里山',
    summary: '樱花云海与小火车，森林之旅经典路线。',
    cover_url: 'assets/spots/Taiwan_Alishan.avif',
    province: '台湾省',
  },
  {
    slug: '垦丁',
    name: '垦丁',
    summary: '海角天涯风吹草低，海岸珊瑚礁风光。',
    cover_url: 'assets/spots/Taiwan_Kending.avif',
    province: '台湾省',
  },
  // 香港特别行政区
  {
    slug: '维多利亚港',
    name: '维多利亚港',
    summary: '灯火璀璨的东方之珠，海湾夜景流光溢彩。',
    cover_url: 'assets/spots/HongKong_WeiduoliyaGang.avif',
    province: '香港特别行政区',
  },
  {
    slug: '太平山顶',
    name: '太平山顶',
    summary: '凌霄俯瞰维港，城海天际线一览无遗。',
    cover_url: 'assets/spots/HongKong_TaipingShanding.avif',
    province: '香港特别行政区',
  },
  {
    slug: '香港迪士尼',
    name: '香港迪士尼',
    summary: '奇妙童话王国，亲子游与梦幻体验乐园闻名。',
    cover_url: 'assets/spots/HongKong_Disini.avif',
    province: '香港特别行政区',
  },

  // 澳门特别行政区
  {
    slug: '大三巴牌坊',
    name: '大三巴牌坊',
    summary: '石砌巴洛克教堂立面，见证中西文化交融。',
    cover_url: 'assets/spots/Macau_DasanbaPaifang.avif',
    province: '澳门特别行政区',
  },
  {
    slug: '官也街',
    name: '官也街',
    summary: '氹仔旧城巷弄间，葡式风情与美食荟萃。',
    cover_url: 'assets/spots/Macau_GuanYeJie.avif',
    province: '澳门特别行政区',
  },
  {
    slug: '新葡京',
    name: '新葡京',
    summary: '莲花造型摩天地标，霓虹闪烁的城市名片。',
    cover_url: 'assets/spots/Macau_XinPujing.avif',
    province: '澳门特别行政区',
  },
  // 贵州省
  {
    slug: '黄果树瀑布',
    name: '黄果树瀑布',
    summary: '中国最大瀑布群，水帘洞与水势如龙闻名。',
    cover_url: 'assets/spots/Guizhou_Huangguoshu.avif',
    province: '贵州省',
  },
  {
    slug: '西江千户苗寨',
    name: '西江千户苗寨',
    summary: '层叠吊脚楼与苗族风情，夜色灯火璀璨。',
    cover_url: 'assets/spots/Guizhou_XijiangQianhuMiaozhai.avif',
    province: '贵州省',
  },
  {
    slug: '梵净山',
    name: '梵净山',
    summary: '金顶红云缭绕，古佛道场云中仙山。',
    cover_url: 'assets/spots/Guizhou_Fanjingshan.avif',
    province: '贵州省',
  },
  // 云南省
  {
    slug: '丽江古城',
    name: '丽江古城',
    summary: '纳西风情小桥流水，四方街古韵悠长。',
    cover_url: 'assets/spots/Yunnan_LijiangGucheng.avif',
    province: '云南省',
  },
  {
    slug: '洱海',
    name: '洱海',
    summary: '风花雪月之境，苍山洱海相映成趣。',
    cover_url: 'assets/spots/Yunnan_Erhai.avif',
    province: '云南省',
  },
  {
    slug: '玉龙雪山',
    name: '玉龙雪山',
    summary: '冰川雪峰拔地而起，蓝月谷碧水如镜。',
    cover_url: 'assets/spots/Yunnan_YulongXueshan.avif',
    province: '云南省',
  },
  {
    slug: '西双版纳',
    name: '西双版纳',
    summary: '热带雨林与傣族风情，生物多样的天堂。',
    cover_url: 'assets/spots/Yunnan_Xishuangbanna.avif',
    province: '云南省',
  },
];
