export const SCENES = [
  // 北京市
  {
    slug: '故宫',
    name: '故宫',
    summary: '故宫，又称紫禁城，是明清两代的皇家宫殿。这里是中国古代宫廷建筑之精华，汇聚了无数珍贵文物，展现了中国古代皇家的威严与登峰造极的工艺水平。',
    cover_url: 'assets/spots/Beijing_Gugong.avif',
    province: '北京市',
  },
  {
    slug: '长城',
    name: '长城',
    summary: '长城是中国古代的伟大防御工程，它蜿蜒数千里，横亘在华北的崇山峻岭之上。它不仅是中华民族智慧的结晶，也是坚韧不屈精神的象征。',
    cover_url: 'assets/spots/Beijing_Changcheng.avif',
    province: '北京市',
  },
  {
    slug: '颐和园',
    name: '颐和园',
    summary: '颐和园是中国现存规模最大、保存最完整的皇家园林。它巧妙地融合了江南园林的秀美风韵与北方宫苑的宏大气派，湖光山色与亭台楼阁交相辉映。',
    cover_url: 'assets/spots/Beijing_Yiheyuan.avif',
    province: '北京市',
  },
  {
    slug: '天坛',
    name: '天坛',
    summary: '天坛是明清两代皇帝祭祀皇天、祈五谷丰登的场所。其建筑布局庄严典雅，独特的天心石和回音壁等设计，体现了古人对“天”的崇高敬意。',
    cover_url: 'assets/spots/Beijing_Tiantan.avif',
    province: '北京市',
  },
  // 天津市
  {
    slug: '古文化街',
    name: '古文化街',
    summary: '天津古文化街是感受津门历史风韵的绝佳去处。街道两旁是仿清代民间小式店铺，汇集了众多老字号和民间手工艺品，如泥人张、杨柳青年画等。',
    cover_url: 'assets/spots/Tianjin_GuwenhuaJie.avif',
    province: '天津市',
  },
  {
    slug: '意式风情区',
    name: '意式风情区',
    summary: '天津意式风情区曾是意大利在境外的唯一租界。这里保存了完整的欧洲建筑群，漫步其中，仿佛置身于马可波罗广场，感受着近代天津的异域风情与历史变迁。',
    cover_url: 'assets/spots/Tianjin_YishiFengqingQu.avif',
    province: '天津市',
  },
  {
    slug: '海河',
    name: '海河',
    summary: '海河是天津的母亲河，它蜿蜒穿城而过。河岸两侧，欧式历史建筑与现代摩天大楼交相辉映，构成天津独特的城市天际线，夜景尤为迷人。',
    cover_url: 'assets/spots/Tianjin_Haihe.avif',
    province: '天津市',
  },
  // 河北省
  {
    slug: '避暑山庄',
    name: '避暑山庄',
    summary: '承德避暑山庄是清代皇帝的夏日行宫，也是中国现存最大的皇家园林。它集园林艺术与建筑之大成，湖区、平原区、山区景色各异，宛如中国版图的缩影。',
    cover_url: 'assets/spots/Hebei_Bishushanzhuang.avif',
    province: '河北省',
  },
  {
    slug: '山海关',
    name: '山海关',
    summary: '山海关是明长城的东北关隘之一，被誉为“天下第一关”。它汇聚了长城、关城、海防等多种防御体系，是长城入海的壮丽起点，历史地位极其重要。',
    cover_url: 'assets/spots/Hebei_Shanhaiguan.avif',
    province: '河北省',
  },
  {
    slug: '赵州桥',
    name: '赵州桥',
    summary: '赵州桥建于隋代，是世界上现存年代最久、跨度最大、保存最完整的单孔敞肩石拱桥。它历经千年风雨仍在服役，是中国古代工程技术的奇迹。',
    cover_url: 'assets/spots/Hebei_ZhaozhouQiao.avif',
    province: '河北省',
  },
  // 上海市
  {
    slug: '外滩',
    name: '外滩',
    summary: '外滩是上海的标志性景观，黄浦江畔矗立着数十栋风格迥异的“万国建筑群”。这里见证了上海滩的百年风云，是魔都开埠与繁华的历史缩影。',
    cover_url: 'assets/spots/Shanghai_Waitan.avif',
    province: '上海市',
  },
  {
    slug: '东方明珠',
    name: '东方明珠',
    summary: '东方明珠广播电视塔是上海的城市地标之一。其独特的造型由大小不一的球体串联而成，充满了未来感，登塔可俯瞰黄浦江两岸的壮丽景色。',
    cover_url: 'assets/spots/Shanghai_DongfangMingzhu.avif',
    province: '上海市',
  },
  {
    slug: '豫园',
    name: '豫园',
    summary: '豫园是上海市区内保存最完整的江南古典园林。园内亭台楼阁、假山池沼布局精巧，咫尺之间再造乾坤，展现了明代园林的精致与典雅。',
    cover_url: 'assets/spots/Shanghai_Yuyuan.avif',
    province: '上海市',
  },
  // 山西省
  {
    slug: '平遥古城',
    name: '平遥古城',
    summary: '平遥古城是中国保存最为完好的四大古城之一。它完整保留了明清时期的县城风貌，巍峨的城墙、古老的街巷和曾经辉煌的票号，共同见证了晋商的金融传奇。',
    cover_url: 'assets/spots/Shanxi_PingyaoGucheng.avif',
    province: '山西省',
  },
  {
    slug: '云冈石窟',
    name: '云冈石窟',
    summary: '云冈石窟是北魏时期皇家开凿的佛教艺术瑰宝。石窟依山而建，佛像群雕凿精美，气势恢宏，展现了早期佛教造像艺术的雄浑与壮丽。',
    cover_url: 'assets/spots/Shanxi_YungangShiku.avif',
    province: '山西省',
  },
  {
    slug: '悬空寺',
    name: '悬空寺',
    summary: '悬空寺位于恒山峭壁之上，是一座佛、道、儒三教合一的独特寺庙。它利用力学原理半嵌在悬崖上，木构建筑飞架千年，堪称建筑史上的奇迹。',
    cover_url: 'assets/spots/Shanxi_Xuankongsi.avif',
    province: '山西省',
  },
  // 内蒙古自治区
  {
    slug: '呼伦贝尔',
    name: '呼伦贝尔',
    summary: '呼伦贝尔大草原是中国最广阔的草原之一。这里水草丰美，牛马成群，辽阔的草原与蜿蜒的莫日格勒河交织，四季都展现出壮丽的自然风光。',
    cover_url: 'assets/spots/InnerMongolia_Hulunbuir.avif',
    province: '内蒙古自治区',
  },
  {
    slug: '额济纳',
    name: '额济纳',
    summary: '额济纳以其壮观的胡杨林而闻名于世。每到金秋时节，成片的胡杨林变得绚烂多彩，与荒漠、河流共同构成一幅幅动人心魄的“生而千年不死”的画卷。',
    cover_url: 'assets/spots/InnerMongolia_Ejina.avif',
    province: '内蒙古自治区',
  },
  {
    slug: '成吉思汗陵',
    name: '成吉思汗陵',
    summary: '成吉思汗陵是纪念一代天骄成吉思汗的圣地，也是蒙古族文化的象征。虽然并非其真正的陵寝，但这里常年举行隆重的祭祀活动，承载着蒙古民族的历史记忆。',
    cover_url: 'assets/spots/InnerMongolia_ChinggisMausoleum.avif',
    province: '内蒙古自治区',
  },
  // 辽宁省
  {
    slug: '沈阳故宫',
    name: '沈阳故宫',
    summary: '沈阳故宫是清朝入关前的皇宫，也是中国现存仅次于北京故宫的第二大完整宫殿建筑群。其建筑风格融合了满、汉、蒙、藏特色，独具皇城气象。',
    cover_url: 'assets/spots/Liaoning_ShenyangGugong.avif',
    province: '辽宁省',
  },
  {
    slug: '大连星海广场',
    name: '大连星海广场',
    summary: '星海广场是大连市的城市地标，也是亚洲最大的城市广场。广场设计开阔大气，背靠都市，面向海洋，是市民和游客休闲观光的滨城胜地。',
    cover_url: 'assets/spots/Liaoning_DalianXinghai.avif',
    province: '辽宁省',
  },
  {
    slug: '本溪水洞',
    name: '本溪水洞',
    summary: '本溪水洞是数百万年前形成的大型充水溶洞。游客需乘船进入，洞内暗河潺潺，钟乳石、石笋形态各异，在灯光映衬下，构成一个光怪陆离的地下奇景。',
    cover_url: 'assets/spots/Liaoning_BenxiShuidong.avif',
    province: '辽宁省',
  },
  // 吉林省
  {
    slug: '长白山',
    name: '长白山',
    summary: '长白山是东北亚的生态屏障，以其神秘的天池和壮阔的火山地貌闻名。这里拥有完整的原始森林系统，从山麓到山顶呈现出鲜明的垂直景观带。',
    cover_url: 'assets/spots/Jilin_Changbaishan.avif',
    province: '吉林省',
  },
  {
    slug: '雾凇岛',
    name: '雾凇岛',
    summary: '雾凇岛是观赏吉林雾凇的最佳地点。冬季，不冻的江水蒸腾的水汽遇冷凝结在树枝上，形成晶莹剔透的雾凇景观，宛如童话世界般银装素裹。',
    cover_url: 'assets/spots/Jilin_Wusongdao.avif',
    province: '吉林省',
  },
  {
    slug: '净月潭',
    name: '净月潭',
    summary: '净月潭因形似弯月而得名，是一座大型人工森林水库。这里森林与湖泊相依，四季景色分明，是长春市的“城市后花园”和天然氧吧。',
    cover_url: 'assets/spots/Jilin_JingyueTan.avif',
    province: '吉林省',
  },
  // 黑龙江省
  {
    slug: '哈尔滨冰雪大世界',
    name: '哈尔滨冰雪大世界',
    summary: '哈尔滨冰雪大世界是全球规模最大的冰雪艺术殿堂。每年冬季，这里都会用冰雪雕琢出璀璨的童话王国，冰灯雪雕在夜幕下流光溢彩，蔚为壮观。',
    cover_url: 'assets/spots/Heilongjiang_HarbinIce.avif',
    province: '黑龙江省',
  },
  {
    slug: '雪乡',
    name: '雪乡',
    summary: '雪乡原名双峰林场，因其独特的地理位置导致冬季降雪量极大。厚厚的积雪覆盖在屋顶和木桩上，形成一个个可爱的“雪蘑菇”，尽显极致的北国风光。',
    cover_url: 'assets/spots/Heilongjiang_Xuexiang.avif',
    province: '黑龙江省',
  },
  {
    slug: '五大连池',
    name: '五大连池',
    summary: '五大连池是近代火山喷发后熔岩阻塞河道形成的五个串珠状火山堰塞湖。这里地质奇观遍布，火山、矿泉与湖泊生态系统多样，是一个天然的地质博物馆。',
    cover_url: 'assets/spots/Heilongjiang_Wudalianchi.avif',
    province: '黑龙江省',
  },
  // 江苏省
  {
    slug: '苏州园林',
    name: '苏州园林',
    summary: '苏州古典园林是中国园林艺术的杰出典范，讲究“小中见大”和“咫尺山林”。通过巧妙的叠石理水、花木配置，在有限空间内创造出无限意境。',
    cover_url: 'assets/spots/Jiangsu_SuzhouGardens.avif',
    province: '江苏省',
  },
  {
    slug: '拙政园',
    name: '拙政园',
    summary: '拙政园是苏州园林中面积最大、最富盛名的代表作。全园以水为中心，水院深深，亭台楼阁环水而建，布局疏朗自然，充满了江南水乡的婉约诗意。',
    cover_url: 'assets/spots/Jiangsu_Zhuozhengyuan.avif',
    province: '江苏省',
  },
  {
    slug: '夫子庙',
    name: '夫子庙',
    summary: '夫子庙-秦淮风光带是南京历史文化的缩影。这里以孔庙为中心，十里秦淮河穿流而过，古风建筑、市井小吃与桨声灯影交织，展现了金陵的繁华烟火气。',
    cover_url: 'assets/spots/Jiangsu_Fuzimiao.avif',
    province: '江苏省',
  },
  {
    slug: '中山陵',
    name: '中山陵',
    summary: '中山陵是伟大的革命先行者孙中山先生的陵寝，坐落于南京紫金山麓。建筑群采用青瓦白墙，依山而建，气势恢宏，是中国近代建筑史上的丰碑。',
    cover_url: 'assets/spots/Jiangsu_Zhongshanling.avif',
    province: '江苏省',
  },
  // 浙江省
  {
    slug: '西湖',
    name: '西湖',
    summary: '杭州西湖以其“三面云山一面城”的格局闻名天下。无论是苏堤春晓、断桥残雪，还是雷峰夕照，西湖的诗画江南之美，使其成为千古传颂的人间天堂。',
    cover_url: 'assets/spots/Zhejiang_Xihu.avif',
    province: '浙江省',
  },
  {
    slug: '乌镇',
    name: '乌镇',
    summary: '乌镇是江南水乡古镇的典型代表，十字形的内河水系将其分为东西南北四栅。古镇保留了晚清和民国时期的建筑风貌，枕水人家，小桥流水，古意盎然。',
    cover_url: 'assets/spots/Zhejiang_Wuzhen.avif',
    province: '浙江省',
  },
  {
    slug: '普陀山',
    name: '普陀山',
    summary: '普陀山是观音菩萨的道场，也是中国佛教四大名山之一。它以其神奇、圣洁、清净的“海天佛国”著称，山海风光与袅袅梵音融为一体。',
    cover_url: 'assets/spots/Zhejiang_PutuoShan.avif',
    province: '浙江省',
  },
  {
    slug: '千岛湖',
    name: '千岛湖',
    summary: '千岛湖是为兴建新安江水电站而蓄水形成的人工湖。湖中星罗棋布着一千多个大小岛屿，湖水清澈见底，水质极佳，被誉为“天下第一秀水”。',
    cover_url: 'assets/spots/Zhejiang_Qiandaohu.avif',
    province: '浙江省',
  },
  // 安徽省
  {
    slug: '黄山',
    name: '黄山',
    summary: '黄山以其“四绝”——奇松、怪石、云海、温泉闻名于世，素有“五岳归来不看山，黄山归来不看岳”的美誉。其独特的峰林景观，如诗如画。',
    cover_url: 'assets/spots/Anhui_Huangshan.avif',
    province: '安徽省',
  },
  {
    slug: '宏村',
    name: '宏村',
    summary: '宏村是徽派古村落的杰出代表，以其独特的“牛形”水系布局而著称。月沼、南湖等水景映衬着黛瓦白墙的马头墙建筑，构成一幅流动的水墨画。',
    cover_url: 'assets/spots/Anhui_Hongcun.avif',
    province: '安徽省',
  },
  {
    slug: '九华山',
    name: '九华山',
    summary: '九华山是地藏菩萨的道场，位列中国佛教四大名山。这里山势雄伟，梵宇林立，香火鼎盛，云雾缭绕间的寺庙更显庄严肃穆。',
    cover_url: 'assets/spots/Anhui_Jiuhuashan.avif',
    province: '安徽省',
  },
  // 福建省
  {
    slug: '鼓浪屿',
    name: '鼓浪屿',
    summary: '鼓浪屿是一座风光秀丽的海岛，岛上保留了大量中西合璧的“万国建筑”。这里没有车马喧嚣，只有琴声与海浪相伴，充满了浪漫文艺的慢时光气息。',
    cover_url: 'assets/spots/Fujian_Gulangyu.avif',
    province: '福建省',
  },
  {
    slug: '武夷山',
    name: '武夷山',
    summary: '武夷山是世界文化与自然双重遗产。这里独特的丹霞峰林与九曲溪流完美结合，乘竹筏漂流其间，可见“碧水丹山”的人间仙境，同时也是大红袍等名茶的产地。',
    cover_url: 'assets/spots/Fujian_Wuyishan.avif',
    province: '福建省',
  },
  {
    slug: '土楼',
    name: '土楼',
    summary: '福建土楼是客家人智慧的结晶，是大型的夯土合院式民居。这些圆形或方形的土楼朴拙厚重，集居住、防御功能于一体，是世界上独一无二的人文奇观。',
    cover_url: 'assets/spots/Fujian_Tulou.avif',
    province: '福建省',
  },
  // 江西省
  {
    slug: '庐山',
    name: '庐山',
    summary: '庐山以其“匡庐奇秀甲天下”而闻名，飞瀑流泉、云烟变幻是其特色。这里不仅自然风光秀丽，更承载了丰富的历史文化，是著名的避暑和人文胜地。',
    cover_url: 'assets/spots/Jiangxi_Lushan.avif',
    province: '江西省',
  },
  {
    slug: '景德镇',
    name: '景德镇',
    summary: '景德镇是享誉世界的“千年瓷都”。这里的制瓷历史悠久，技艺精湛，从宋代的青白瓷到明清的青花、粉彩，每一片瓷器都照见了中华匠心的传承。',
    cover_url: 'assets/spots/Jiangxi_Jingdezhen.avif',
    province: '江西省',
  },
  {
    slug: '婺源',
    name: '婺源',
    summary: '婺源被誉为“中国最美的乡村”。春季，金黄的油菜花海与粉墙黛瓦的徽派古村落交相辉映；秋季，层林尽染的红枫与晒秋人家构成一幅幅田园画卷。',
    cover_url: 'assets/spots/Jiangxi_Wuyuan.avif',
    province: '江西省',
  },
  // 山东省
  {
    slug: '泰山',
    name: '泰山',
    summary: '泰山是“五岳之尊”，自古以来便是帝王封禅、百姓朝拜的圣山。登临岱顶，观云海日出，可体会“会当凌绝顶，一览众山小”的雄伟气魄。',
    cover_url: 'assets/spots/Shandong_Taishan.avif',
    province: '山东省',
  },
  {
    slug: '曲阜',
    name: '曲阜',
    summary: '曲阜是儒家文化的发源地，孔子的故乡。城内的孔庙、孔府、孔林（合称“三孔”）是祭祀孔子、体现儒家思想的物质载体，是全球华人的精神家园。',
    cover_url: 'assets/spots/Shandong_Qufu.avif',
    province: '山东省',
  },
  {
    slug: '崂山',
    name: '崂山',
    summary: '崂山是中国的“海上第一名山”，它一面是奇峰险峻，一面是碧海蓝天。这里也是道教全真派的发祥地之一，山海相依的景观使其独具仙风道骨。',
    cover_url: 'assets/spots/Shandong_Laoshan.avif',
    province: '山东省',
  },
  // 河南省
  {
    slug: '少林寺',
    name: '少林寺',
    summary: '嵩山少林寺是中国禅宗的祖庭，也是少林功夫的发源地。寺内的塔林、古柏和武僧们的演练，共同见证了“禅武合一”的千年传承。',
    cover_url: 'assets/spots/Henan_ShaolinSi.avif',
    province: '河南省',
  },
  {
    slug: '龙门石窟',
    name: '龙门石窟',
    summary: '龙门石窟是中国石刻艺术的宝库，开凿于北魏至北宋时期。伊河两岸的悬崖上密布着十万余尊佛像造像，尤以奉先寺卢舍那大佛最能体现盛唐气象。',
    cover_url: 'assets/spots/Henan_LongmenShiku.avif',
    province: '河南省',
  },
  {
    slug: '云台山',
    name: '云台山',
    summary: '云台山以其独特的“北方岩溶地貌”被列为世界地质公园。景区内的红石峡丹崖碧水，潭瀑峡九步一潭，展现了太行山水刚柔并济的灵动之美。',
    cover_url: 'assets/spots/Henan_Yuntaishan.avif',
    province: '河南省',
  },
  // 湖北省
  {
    slug: '黄鹤楼',
    name: '黄鹤楼',
    summary: '黄鹤楼矗立于长江之畔，自古便是“天下江山第一楼”。它历经损毁与重建，承载了无数文人墨客的诗意与传说，是武汉市的标志性建筑。',
    cover_url: 'assets/spots/Hubei_Huanghelou.avif',
    province: '湖北省',
  },
  {
    slug: '三峡大坝',
    name: '三峡大坝',
    summary: '三峡大坝是当今世界规模最大的水利枢纽工程。这座巨坝横跨长江，展现了人类改造自然的磅礴力量，在高峡平湖间形成了壮观的工业景观。',
    cover_url: 'assets/spots/Hubei_ThreeGorgesDam.avif',
    province: '湖北省',
  },
  {
    slug: '神农架',
    name: '神农架',
    summary: '神农架林区是中国唯一以“林区”命名的行政区，拥有华中地区最完整的原始森林生态系统。这里是生物多样性的天然宝库，也充满了“野人”的神秘传说。',
    cover_url: 'assets/spots/Hubei_Shennongjia.avif',
    province: '湖北省',
  },
  // 湖南省
  {
    slug: '张家界',
    name: '张家界',
    summary: '张家界国家森林公园以其罕见的石英砂岩峰林地貌闻名。数以千计的石峰拔地而起，形态各异，这里也是电影《阿凡达》中“哈利路亚山”的取景地。',
    cover_url: 'assets/spots/Hunan_Zhangjiajie.avif',
    province: '湖南省',
  },
  {
    slug: '岳阳楼',
    name: '岳阳楼',
    summary: '岳阳楼屹立于洞庭湖畔，是江南三大名楼之一。它因范仲淹的《岳阳楼记》而名扬天下，“先天下之忧而忧，后天下之乐而乐”的情怀使其文脉绵长。',
    cover_url: 'assets/spots/Hunan_YueyangLou.avif',
    province: '湖南省',
  },
  {
    slug: '凤凰古城',
    name: '凤凰古城',
    summary: '凤凰古城是一座具有浓郁苗疆风情的古镇。沱江水缓缓流过，江边的吊脚楼鳞次栉比，古老的石板街与淳朴的民风，使其在夜色中如梦似幻。',
    cover_url: 'assets/spots/Hunan_FenghuangGucheng.avif',
    province: '湖南省',
  },
  // 广东省
  {
    slug: '广州塔',
    name: '广州塔',
    summary: '广州塔昵称“小蛮腰”，是广州市的新地标建筑。其独特的塔体造型和绚丽的夜间灯光，使其成为珠江夜景中最亮丽的风景线，塔顶摩天轮更是极具特色。',
    cover_url: 'assets/spots/Guangdong_GuangzhouTa.avif',
    province: '广东省',
  },
  {
    slug: '丹霞山',
    name: '丹霞山',
    summary: '丹霞山是“丹霞地貌”的命名地，以其赤壁丹崖为特色。这里的山石呈现出艳丽的红色，形态各异，群峰如林，是广东省内最著名的自然风光区。',
    cover_url: 'assets/spots/Guangdong_Danxiashan.avif',
    province: '广东省',
  },
  {
    slug: '白云山',
    name: '白云山',
    summary: '白云山是南粤名山，自古有“羊城第一秀”之称。它位于广州市中心，是城市的“绿肺”，登高可俯瞰广州全景，云山珠水尽收眼底。',
    cover_url: 'assets/spots/Guangdong_Baiyunshan.avif',
    province: '广东省',
  },
  // 广西壮族自治区
  {
    slug: '桂林山水',
    name: '桂林山水',
    summary: '“桂林山水甲天下”早已深入人心。这里典型的喀斯特峰丛地貌与蜿蜒的漓江江流相映成趣，构成一幅幅山青、水秀、洞奇、石美的中国水墨画。',
    cover_url: 'assets/spots/Guangxi_GuilinShanshui.avif',
    province: '广西壮族自治区',
  },
  {
    slug: '阳朔西街',
    name: '阳朔西街',
    summary: '阳朔西街是阳朔最古老繁华的街道，背靠漓江山水画廊。这里中西文化交融，白天是风情小镇，夜晚则化身为热闹的休闲中心，吸引着全球游客。',
    cover_url: 'assets/spots/Guangxi_YangshuoXijie.avif',
    province: '广西壮族自治区',
  },
  {
    slug: '德天瀑布',
    name: '德天瀑布',
    summary: '德天瀑布位于中越边境，是亚洲第一、世界第四大跨国瀑布。瀑布气势磅礴，水幕从高处倾泻而下，轰鸣声震耳欲聋，景色极为壮观。',
    cover_url: 'assets/spots/Guangxi_DetianPubu.avif',
    province: '广西壮族自治区',
  },
  // 海南省
  {
    slug: '三亚',
    name: '三亚',
    summary: '三亚是中国最南端的热带滨海旅游城市。这里拥有得天独厚的阳光、海水、沙滩和椰风海韵，是国内首屈一指的度假胜地和避寒天堂。',
    cover_url: 'assets/spots/Hainan_Sanya.avif',
    province: '海南省',
  },
  {
    slug: '亚龙湾',
    name: '亚龙湾',
    summary: '亚龙湾被誉为“天下第一湾”，以其半月形的海湾、细腻洁白的沙滩和清澈的海水而闻名。这里风浪平缓，是进行水上运动和潜水的理想之地。',
    cover_url: 'assets/spots/Hainan_YalongWan.avif',
    province: '海南省',
  },
  {
    slug: '蜈支洲岛',
    name: '蜈支洲岛',
    summary: '蜈支洲岛海水清澈见底，能见度极高，被称作“中国的马尔代夫”。岛屿周围环绕着丰富的珊瑚礁，是国内最顶级的潜水天堂之一。',
    cover_url: 'assets/spots/Hainan_WuzhizhouDao.avif',
    province: '海南省',
  },
  // 重庆市
  {
    slug: '洪崖洞',
    name: '洪崖洞',
    summary: '洪崖洞是以巴渝传统吊脚楼风貌为主题的建筑群，依山崖而建。当夜幕降临，灯火辉煌的吊脚楼群极具魔幻色彩，是重庆山城立体夜景的标志性名片。',
    cover_url: 'assets/spots/Chongqing_Hongyadong.avif',
    province: '重庆市',
  },
  {
    slug: '磁器口',
    name: '磁器口',
    summary: '磁器口古镇曾是嘉陵江畔重要的水陆码头。如今，古镇的石板路两旁遍布茶馆、小吃店和手工艺品，保留着浓郁的巴渝风情和市井烟火气。',
    cover_url: 'assets/spots/Chongqing_Ciqikou.avif',
    province: '重庆市',
  },
  {
    slug: '长江索道',
    name: '长江索道',
    summary: '长江索道是重庆独特的交通工具，被誉为“空中巴士”。乘坐索道跨越长江，可以从空中俯瞰两岸鳞次栉比的建筑和立体山城风貌，视野极佳。',
    cover_url: 'assets/spots/Chongqing_ChangjiangSuodao.avif',
    province: '重庆市',
  },
  // 四川省
  {
    slug: '宽窄巷子',
    name: '宽窄巷子',
    summary: '宽窄巷子由宽巷子、窄巷子和井巷子三条平行的老式街道组成，是成都老城生活的样本。这里青瓦灰墙的四合院落，融合了现代休闲与传统雅致。',
    cover_url: 'assets/spots/Sichuan_KuanzhaiXiangzi.avif',
    province: '四川省',
  },
  {
    slug: '九寨沟',
    name: '九寨沟',
    summary: '九寨沟因沟内有九个藏族村寨而得名，以其五彩池、雪山、瀑布群和原始森林著称。这里的水色变幻无穷，四季景色皆如画，被誉为“童话世界”和“人间仙境”。',
    cover_url: 'assets/spots/Sichuan_Jiuzhaigou.avif',
    province: '四川省',
  },
  {
    slug: '峨眉山',
    name: '峨眉山',
    summary: '峨眉山是普贤菩萨的道场，中国佛教四大名山之一。山势雄伟，林海苍翠，登临金顶可观云海、佛光、日出等奇观，是清凉的避暑和朝圣之地。',
    cover_url: 'assets/spots/Sichuan_EMeiShan.avif',
    province: '四川省',
  },
  {
    slug: '都江堰',
    name: '都江堰',
    summary: '都江堰是战国时期修建的大型水利工程，至今仍在发挥作用。它巧妙地利用自然地理条件，实现了自动分水、泄洪、排沙，使川西平原成为“天府之国”。',
    cover_url: 'assets/spots/Sichuan_Dujiangyan.avif',
    province: '四川省',
  },
  // 西藏自治区
  {
    slug: '布达拉宫',
    name: '布达拉宫',
    summary: '布达拉宫是雪域高原的圣城拉萨的标志性建筑。这座依山而建、气势雄伟的宫堡式建筑群，曾是历代达赖喇嘛的冬宫，其红白宫殿辉映着藏地文明的辉煌。',
    cover_url: 'assets/spots/Tibet_PutalaGong.avif',
    province: '西藏自治区',
  },
  {
    slug: '纳木错',
    name: '纳木错',
    summary: '纳木错是西藏三大圣湖之一，也是世界上海拔最高的大型湖泊。它静卧在念青唐古拉山脚下，湖水湛蓝纯净，如同镶嵌在高原上的一块巨大蓝宝石。',
    cover_url: 'assets/spots/Tibet_Namucuo.avif',
    province: '西藏自治区',
  },
  {
    slug: '珠峰大本营',
    name: '珠峰大本营',
    summary: '珠峰大本营是为攀登珠穆朗玛峰而设立的基地，也是普通游客仰望世界之巅的最佳位置。在这里，皑皑雪峰近在咫尺，可以深切感受大自然的雄伟与震撼。',
    cover_url: 'assets/spots/Tibet_ZhufengDibenying.avif',
    province: '西藏自治区',
  },
  // 陕西省
  {
    slug: '兵马俑',
    name: '兵马俑',
    summary: '秦始皇兵马俑是秦始皇陵的陪葬坑，被誉为“世界第八大奇迹”。这支庞大的地下军阵，以其真人大小的陶俑和青铜兵器，展现了秦帝国的强大威仪。',
    cover_url: 'assets/spots/Shaanxi_Bingmayong.avif',
    province: '陕西省',
  },
  {
    slug: '华清池',
    name: '华清池',
    summary: '华清池（华清宫）是唐代皇家御用温泉别苑。这里不仅因杨贵妃“温泉水滑洗凝脂”而闻名，也是“西安事变”的发生地，承载着盛唐故事与近代风云。',
    cover_url: 'assets/spots/Shaanxi_Huaqingchi.avif',
    province: '陕西省',
  },
  {
    slug: '大雁塔',
    name: '大雁塔',
    summary: '大雁塔位于大慈恩寺内，是玄奘法师为保存从西域取回的经卷佛像而督建。这座千年古塔是古都长安的象征，登塔可俯瞰西安城南风光。',
    cover_url: 'assets/spots/Shaanxi_DayanTa.avif',
    province: '陕西省',
  },
  {
    slug: '华山',
    name: '华山',
    summary: '华山以“奇险天下第一山”著称，五峰耸立，绝壁千仞。其长空栈道、鹞子翻身等险道极具挑战性，是登山爱好者和武侠文化迷向往之地。',
    cover_url: 'assets/spots/Shaanxi_Huashan.avif',
    province: '陕西省',
  },
  // 甘肃省
  {
    slug: '敦煌',
    name: '敦煌',
    summary: '敦煌是古丝绸之路上的重镇。这里的大漠风光雄浑壮丽，“大漠孤烟直”的景象随处可见，而月牙泉与鸣沙山相依相伴的奇观更是令人称奇。',
    cover_url: 'assets/spots/Gansu_Dunhuang.avif',
    province: '甘肃省',
  },
  {
    slug: '莫高窟',
    name: '莫高窟',
    summary: '莫高窟，俗称千佛洞，是世界上现存规模最大、内容最丰富的佛教艺术宝库。洞窟内精美的壁画和彩塑，历经千年岁月，依然展现着辉煌璀璨的艺术成就。',
    cover_url: 'assets/spots/Gansu_MogaoKu.avif',
    province: '甘肃省',
  },
  {
    slug: '嘉峪关',
    name: '嘉峪关',
    summary: '嘉峪关是明长城的西端起点，也是长城沿线最雄伟的关城。它孤峙于戈壁之上，遥望祁连雪山，尽显“天下第一雄关”的苍凉与坚毅。',
    cover_url: 'assets/spots/Gansu_Jiayuguan.avif',
    province: '甘肃省',
  },
  {
    slug: '张掖丹霞',
    name: '张掖丹霞',
    summary: '张掖丹霞地貌以其色彩斑斓的丘陵景观而闻名。数以亿年的地质运动，将这里的岩石雕琢成流霞溢彩的彩带，如同上帝打翻的调色盘，视觉效果极为震撼。',
    cover_url: 'assets/spots/Gansu_ZhangyeDanxia.avif',
    province: '甘肃省',
  },
  // 青海省
  {
    slug: '青海湖',
    name: '青海湖',
    summary: '青海湖是中国最大的内陆咸水湖。这片高原上的湛蓝大湖，四周被高山环抱，夏季湖畔的草海与金黄的油菜花田相映成辉，景色壮美。',
    cover_url: 'assets/spots/Qinghai_QinghaiHu.avif',
    province: '青海省',
  },
  {
    slug: '茶卡盐湖',
    name: '茶卡盐湖',
    summary: '茶卡盐湖是一座天然结晶盐湖，湖面如镜，倒映着蓝天白云。游客可以赤脚走上湖面，仿佛漫步云端，因此被誉为中国的“天空之境”。',
    cover_url: 'assets/spots/Qinghai_ChakaYanhua.avif',
    province: '青海省',
  },
  {
    slug: '塔尔寺',
    name: '塔尔寺',
    summary: '塔尔寺是藏传佛教格鲁派（黄教）的六大寺院之一，也是宗喀巴大师的诞生地。寺内的壁画、堆绣和酥油花被誉为“艺术三绝”，工艺绝伦。',
    cover_url: 'assets/spots/Qinghai_Taersi.avif',
    province: '青海省',
  },
  // 宁夏回族自治区
  {
    slug: '沙坡头',
    name: '沙坡头',
    summary: '沙坡头集大漠、黄河、高山、绿洲于一体。这里一边是腾格里沙漠的浩瀚，一边是黄河的奔流不息，独特的“沙山北面坡”治沙奇迹也蜚声中外。',
    cover_url: 'assets/spots/Ningxia_Shapotou.avif',
    province: '宁夏回族自治区',
  },
  {
    slug: '沙湖',
    name: '沙湖',
    summary: '沙湖是宁夏的王牌景点，以其“沙、水、苇、鸟、山”五景合一的独特景观而著称。在广袤的沙漠中能有如此大面积的湖泊和芦苇荡，实属罕见，也是候鸟的天堂。',
    cover_url: 'assets/spots/Ningxia_Shahu.avif',
    province: '宁夏回族自治区',
  },
  {
    slug: '镇北堡',
    name: '镇北堡',
    summary: '镇北堡西部影城原是明清时期的边防古堡。这里以其苍凉、原始的黄土风貌，成为众多知名电影（如《大话西游》）的取景地，被誉为“中国电影从这里走向世界”。',
    cover_url: 'assets/spots/Ningxia_Zhenbeibao.avif',
    province: '宁夏回族自治区',
  },
  // 新疆维吾尔自治区
  {
    slug: '喀纳斯',
    name: '喀纳斯',
    summary: '喀纳斯湖是坐落在阿尔泰深山密林中的高山冷水湖。湖水会随着季节和光线变化呈现不同色彩，四周环绕着茂密的冷杉林，宛如北欧童话般的秘境。',
    cover_url: 'assets/spots/Xinjiang_Kanas.avif',
    province: '新疆维吾尔自治区',
  },
  {
    slug: '天山天池',
    name: '天山天池',
    summary: '天山天池古称“瑶池”，是一座著名的高山堰塞湖。它背靠雄伟的博格达峰，湖水清澈碧透，四周雪峰环抱，是新疆天山山脉中的一颗明珠。',
    cover_url: 'assets/spots/Xinjiang_TianshanTianchi.avif',
    province: '新疆维吾尔自治区',
  },
  {
    slug: '赛里木湖',
    name: '赛里木湖',
    summary: '赛里木湖被誉为“大西洋的最后一滴眼泪”，是新疆海拔最高、面积最大的高山湖泊。夏季湖畔花海草甸连绵不绝，与湛蓝的湖水和远方雪山构成绝美画卷。',
    cover_url: 'assets/spots/Xinjiang_SailimuHu.avif',
    province: '新疆维吾尔自治区',
  },
  {
    slug: '火焰山',
    name: '火焰山',
    summary: '火焰山位于吐鲁番盆地，是《西游记》中家喻户晓的地名。这里的红色砂岩山岭在夏季酷热的气温下，热浪滚滚，赤褐色的山体在阳光下仿佛烈焰燃烧。',
    cover_url: 'assets/spots/Xinjiang_Huoyanshan.avif',
    province: '新疆维吾尔自治区',
  },
  // 台湾省
  {
    slug: '台北',
    name: '台北',
    summary: '台北是台湾的政治经济文化中心，一座现代与传统交织的都市。这里不仅有101大楼等地标，也有故宫博物院的人文底蕴，更有士林夜市等充满活力的市井小吃。',
    cover_url: 'assets/spots/Taiwan_Taibei.avif',
    province: '台湾省',
  },
  {
    slug: '日月潭',
    name: '日月潭',
    summary: '日月潭是台湾最大的天然湖泊，湖中央的拉鲁岛将其分为日潭和月潭。湖面群山环绕，碧波荡漾，清晨的薄雾缭绕其间，景色静谧如诗。',
    cover_url: 'assets/spots/Taiwan_RiyueTan.avif',
    province: '台湾省',
  },
  {
    slug: '阿里山',
    name: '阿里山',
    summary: '阿里山以其日出、云海、晚霞、森林和小火车“五奇”闻名。春季的樱花盛开，与高山森林景观相映成趣，乘坐小火车穿梭林间是经典体验。',
    cover_url: 'assets/spots/Taiwan_Alishan.avif',
    province: '台湾省',
  },
  {
    slug: '垦丁',
    name: '垦丁',
    summary: '垦丁位于台湾岛的最南端，以其热带海岸风光和珊瑚礁地貌著称。这里的“海角天涯”风光、鹅銮鼻灯塔以及风吹草低的龙磐公园，都极具特色。',
    cover_url: 'assets/spots/Taiwan_Kending.avif',
    province: '台湾省',
  },
  // 香港特别行政区
  {
    slug: '维多利亚港',
    name: '维多利亚港',
    summary: '维多利亚港是香港繁荣的象征，其海湾夜景被誉为世界三大夜景之一。两岸摩天大楼林立，入夜后流光溢彩，天星小轮穿梭其间，尽显“东方之珠”的璀璨。',
    cover_url: 'assets/spots/HongKong_WeiduoliyaGang.avif',
    province: '香港特别行政区',
  },
  {
    slug: '太平山顶',
    name: '太平山顶',
    summary: '太平山顶是俯瞰维多利亚港和香港全景的最佳地点。乘坐古老的山顶缆车登山，在凌霄阁观景台，可以将香港的城、海、天际线一览无遗。',
    cover_url: 'assets/spots/HongKong_TaipingShanding.avif',
    province: '香港特别行政区',
  },
  {
    slug: '香港迪士尼',
    name: '香港迪士尼',
    summary: '香港迪士尼乐园是全球最小的迪士尼乐园之一，但充满了奇妙的童话氛围。这里是亲子游的绝佳选择，经典的游乐设施和梦幻的烟火表演深受喜爱。',
    cover_url: 'assets/spots/HongKong_Disini.avif',
    province: '香港特别行政区',
  },

  // 澳门特别行政区
  {
    slug: '大三巴牌坊',
    name: '大三巴牌坊',
    summary: '大三巴牌坊是圣保禄教堂被焚毁后留下的前壁立面，是澳门的标志性建筑。这座石砌的巴洛克风格牌坊，精雕细琢，见证了四百多年中西文化的交融。',
    cover_url: 'assets/spots/Macau_DasanbaPaifang.avif',
    province: '澳门特别行政区',
  },
  {
    slug: '官也街',
    name: '官也街',
    summary: '官也街是澳门氹仔旧城区的中心巷弄。这条不长的小街汇聚了无数地道的澳门美食，如猪扒包、蛋挞和各种手信，葡式风情建筑也使其充满魅力。',
    cover_url: 'assets/spots/Macau_GuanYeJie.avif',
    province: '澳门特别行政区',
  },
  {
    slug: '新葡京',
    name: '新葡京',
    summary: '新葡京酒店以其独特的莲花造型成为澳门的摩天地标。其建筑设计极尽奢华，内部装饰金碧辉煌，霓虹闪烁的莲花造型在夜色中是澳门最耀眼的城市名片。',
    cover_url: 'assets/spots/Macau_XinPujing.avif',
    province: '澳门特别行政区',
  },
  // 贵州省
  {
    slug: '黄果树瀑布',
    name: '黄果树瀑布',
    summary: '黄果树瀑布是中国最大的瀑布群，也是世界上唯一可以从上下、前后、左右六个方位观赏的瀑布。其水势浩大，声如奔雷，水帘洞更是奇特。',
    cover_url: 'assets/spots/Guizhou_Huangguoshu.avif',
    province: '贵州省',
  },
  {
    slug: '西江千户苗寨',
    name: '西江千户苗寨',
    summary: '西江千户苗寨是目前中国乃至全世界最大的苗族聚居村寨。上千座吊脚楼依山而建，层层叠叠，极具视觉冲击力，夜晚灯火璀璨，宛如星河。',
    cover_url: 'assets/spots/Guizhou_XijiangQianhuMiaozhai.avif',
    province: '贵州省',
  },
  {
    slug: '梵净山',
    name: '梵净山',
    summary: '梵净山是武陵山脉的主峰，以其“金顶红云”和奇特的蘑菇石而闻名。作为弥勒菩萨的道场，这座云中仙山是世界自然遗产，生态原始，景观独特。',
    cover_url: 'assets/spots/Guizhou_Fanjingshan.avif',
    province: '贵州省',
  },
  // 云南省
  {
    slug: '丽江古城',
    name: '丽江古城',
    summary: '丽江古城又名大研古镇，以其浓郁的纳西族风情和小桥流水的布局著称。古城没有城墙，四方街是其中心，古老的石板路和木结构房屋充满了悠闲古韵。',
    cover_url: 'assets/spots/Yunnan_LijiangGucheng.avif',
    province: '云南省',
  },
  {
    slug: '洱海',
    name: '洱海',
    summary: '洱海是大理“风花雪月”四大名景之一，形如人耳。它虽名为海，实为高原湖泊。骑行环游洱海，苍山在侧，碧波荡漾，是感受大理风情的最佳方式。',
    cover_url: 'assets/spots/Yunnan_Erhai.avif',
    province: '云南省',
  },
  {
    slug: '玉龙雪山',
    name: '玉龙雪山',
    summary: '玉龙雪山是纳西族的神山，主峰扇子陡终年积雪。山下的蓝月谷湖水碧绿如玉，与雪山冰川相映成辉，是丽江最具代表性的自然景观。',
    cover_url: 'assets/spots/Yunnan_YulongXueshan.avif',
    province: '云南省',
  },
  {
    slug: '西双版纳',
    name: '西双版纳',
    summary: '西双版纳以其神奇的热带雨林自然景观和浓郁的傣族风情闻名。这里是生物多样性的天堂，也是体验泼水节狂欢、感受南传佛教文化的理想之地。',
    cover_url: 'assets/spots/Yunnan_Xishuangbanna.avif',
    province: '云南省',
  },
];